<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NSLoggerSharp\NSLoggerSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Zeroconf" Version="3.6.11" />
  </ItemGroup>

</Project>
